version: '3'
services:
  web:
    build: .
    container_name: web
    ports:
      - "80:80"
    links:
      - php
      - db:mysql_db
    depends_on:
      - db
      - php
    volumes:
      - ./code:/app
  php:
    build:
      context: ./php/
      dockerfile: Dockerfile
    container_name: php
    links:
      - db:mysql_db
    depends_on:
      - db
    volumes:
      - ./code:/app
  db:
   image: mysql:5.7
   container_name: db
   ports:
      - "3306"
   environment:
      - MYSQL_ROOT_PASSWORD=qrr0
      - MYSQL_DATABASE=notificaciones
   volumes:
      - ./code/SQL/:/docker-entrypoint-initdb.d/
      - ./mysql_dbs:/var/lib/mysql
