version: '3'
services:
  web:
    image: nginx:latest
    container_name: web
    ports:
      - "8080:80"
    links:
      - php
      - db:mysql_db
    depends_on:
      - db
      - php
    volumes:
      - /home/centos/automaticNotificationUpdate/code:/app
      - /home/centos/automaticNotificationUpdate/app.conf:/etc/nginx/conf.d/app.conf
  php:
    build:
      context: .
      dockerfile: Dockerfile_php
    container_name: php
    links:
      - db:mysql_db
    depends_on:
      - db
    volumes:
      - /home/centos/automaticNotificationUpdate/code:/app
  db:
   build: .
   container_name: db
   ports:
      - "3306"
